# Generated by Django 4.2.7 on 2025-07-01 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Zamanı')),
                ('record_count', models.IntegerField(help_text='Bu dosyadan kaç adet log kaydı eklendi', verbose_name='Kayıt Sayısı')),
                ('success', models.BooleanField(default=True, verbose_name='Başarılı')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yükleme Geçmişi',
                'verbose_name_plural': 'Yükleme Geçmişleri',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_time', models.DateTimeField(help_text='Log kaydının alındığı tarih ve saat', verbose_name='Alınma Zamanı')),
                ('type', models.CharField(help_text='Log türü (vulnerability, intrusion, etc.)', max_length=100, verbose_name='Tip')),
                ('severity', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], help_text='Güvenlik olayının önem derecesi', max_length=50, verbose_name='Önem Derecesi')),
                ('threat', models.TextField(help_text='Tespit edilen tehdit açıklaması', verbose_name='Tehdit')),
                ('source_ip', models.GenericIPAddressField(help_text='Tehdidi oluşturan IP adresi', verbose_name='Kaynak IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('uploaded_by', models.ForeignKey(help_text='Bu log kaydını sisteme yükleyen kullanıcı', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Log Kaydı',
                'verbose_name_plural': 'Log Kayıtları',
                'ordering': ['-receive_time'],
                'indexes': [models.Index(fields=['receive_time'], name='logs_log_receive_cc95a1_idx'), models.Index(fields=['severity'], name='logs_log_severit_70ce2b_idx'), models.Index(fields=['source_ip'], name='logs_log_source__1df8ec_idx'), models.Index(fields=['type'], name='logs_log_type_727bbc_idx')],
            },
        ),
    ]
